//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpgradeCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpgradeCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string CONFIG_KEY_FORM_TITLE {
            get {
                return ResourceManager.GetString("CONFIG_KEY_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string CONFIG_KEY_PORT {
            get {
                return ResourceManager.GetString("CONFIG_KEY_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemotingServiceEnabled 的本地化字符串。
        /// </summary>
        internal static string CONFIG_KEY_REMOTE {
            get {
                return ResourceManager.GetString("CONFIG_KEY_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除： 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除文件 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要关闭升级中心服务吗？ 的本地化字符串。
        /// </summary>
        internal static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本格式输入不正确！ 的本地化字符串。
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新时间： 的本地化字符串。
        /// </summary>
        internal static string LatestUpdateTime {
            get {
                return ResourceManager.GetString("LatestUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新综合版本： 的本地化字符串。
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string MessageTip {
            get {
                return ResourceManager.GetString("MessageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新： 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增： 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要删除的文件 的本地化字符串。
        /// </summary>
        internal static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无版本变动 的本地化字符串。
        /// </summary>
        internal static string NothingChanged {
            get {
                return ResourceManager.GetString("NothingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该文件已经存在，不能重复添加！ 的本地化字符串。
        /// </summary>
        internal static string RepeatedAddition {
            get {
                return ResourceManager.GetString("RepeatedAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 综合版本更新为： 的本地化字符串。
        /// </summary>
        internal static string UpdatedVersion {
            get {
                return ResourceManager.GetString("UpdatedVersion", resourceCulture);
            }
        }
    }
}
